### ISSUE TITLE
empty stack

### ISSUE THREAD

**Issue by kumavis** [wanderer/merkle-patricia-tree#3]
somehow we got to a place where we're popping an empty stack. not sure how to debug, the code is a little dense.
```
/Users/kumavis/Development/Node/vapor-rpc/node_modules/node-ethereum/node_modules/ethereumjs-lib/node_modules/merkle-patricia-tree/index.js:285
  if (lastNode.type === 'branch') {
              ^
TypeError: Cannot read property 'type' of undefined
    at internals.Trie._updateNode (/Users/kumavis/Development/Node/vapor-rpc/node_modules/node-ethereum/node_modules/ethereumjs-lib/node_modules/merkle-patricia-tree/index.js:285:15)
    at /Users/kumavis/Development/Node/vapor-rpc/node_modules/node-ethereum/node_modules/ethereumjs-lib/node_modules/merkle-patricia-tree/index.js:106:18
    at processNode (/Users/kumavis/Development/Node/vapor-rpc/node_modules/node-ethereum/node_modules/ethereumjs-lib/node_modules/merkle-patricia-tree/index.js:154:7)
    at /Users/kumavis/Development/Node/vapor-rpc/node_modules/node-ethereum/node_modules/ethereumjs-lib/node_modules/merkle-patricia-tree/index.js:565:9
    at Stream.<anonymous> (/Users/kumavis/Development/Node/vapor-rpc/node_modules/multilevel/node_modules/rpc-stream/index.js:77:10)
    at Stream.stream.write (/Users/kumavis/Development/Node/vapor-rpc/node_modules/multilevel/node_modules/rpc-stream/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at Stream.<anonymous> (/Users/kumavis/Development/Node/vapor-rpc/node_modules/multilevel/node_modules/mux-demux/inject.js:61:14)
    at Stream.emit (events.js:107:17)
    at Stream.stream.emit (/Users/kumavis/Development/Node/vapor-rpc/node_modules/multilevel/node_modules/mux-demux/node_modules/stream-serializer/index.js:60:33)
    at Stream.stream.write (/Users/kumavis/Development/Node/vapor-rpc/node_modules/multilevel/node_modules/mux-demux/node_modules/duplex/index.js:68:12)
    at parse (/Users/kumavis/Development/Node/vapor-rpc/node_modules/multilevel/node_modules/mux-demux/node_modules/stream-serializer/index.js:29:13)
    at Stream.onData [as write] (/Users/kumavis/Development/Node/vapor-rpc/node_modules/multilevel/node_modules/mux-demux/node_modules/stream-serializer/index.js:36:7)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

**Comment by kumavis** [comment]
this is an error triggered by sqldown
